export const configText ={
    hodap_qhqg: {
        id: 'STT',
        ten: 'Tên công trình',
        x: 'Toạ độ X',
        y: 'Toạ độ Y',
        Xa: 'Xã',
        huyen: 'Huyện',
        tinh: 'Tỉnh',
        phanloai: 'Phân loại',
        capquanly: 'Cấp quản lý',
        capkt: 'Cấp kỹ thuật',
        flv_km2: 'Diện tích lưu vực',
        wtb_trm3: 'Dung tích toàn bộ',
        whi: 'Dung tích hữu ích',
        wc: 'Dung tích chết',
        wpl_trm3: 'Dung tích phòng lũ',
        qmay: 'Q phát điện',
        mndbt: 'Mực nước dâng bình thường',
        mnc: 'Mực nước chết',
        mnltk: 'Mực nước lũ thiết kế',
        zdinhdap: 'Cao trình đỉnh đập',
        zdaydap: 'Cao trình đáy đập',
        ldap: 'Chiều dài đập',
        tran: 'Loại tràn',
        sokhoang: 'Số khoang tràn',
        ztran: 'Cao trình tràn',
        btran: 'Bề rộng tràn',
        qxa_ltk: 'Lưu lượng xả lũ thiết kế',
        donviql: 'Đơn vị quản lý',
        xdstart: 'Năm xây dựng',
        xdend: 'năm hoàn thành',
        tinhtrang: 'Tình trạng ',
        // nguon: 'nguon',
        // phanloai1: 'phanloai1',
    },
    cong_qhqg: {
        id: 'STT',
        ten: 'Tên công trình',
        X: 'Toạ độ X',
        Y: 'Toạ độ Y',
        xa: 'Xã',
        tenhuyen: 'Huyện',
        tentinh: 'Tỉnh',
        phanloai: 'Phân loại',
        capquanly: 'Cấp quản lý',
        capkythuat: 'Cấp kỹ thuật',
        khaudo: 'Khẩu độ',
        Zday: 'Cao trình đáy',
        ftuoiha: 'Diện tích tưới thiết kế',
        ftieuha: 'Diện tích tiêu thiết kế',
        donviql: 'Đơn vị quản lý',
        xdstart: 'Năm xây dựng',
        xdend: 'Năm hoàn thành',
        // tinhtrang: 'tinhtrang',
        // geo: 'geo',
        // nguon: 'nguon',
        // ngaythunha: 'ngaythunha',
        // ngaycapnha: 'ngaycapnha',
        // phanloai1: 'phanloai1',
    },
    trambom_ht:{
        FID: 'STT',
        ten: 'Tên công trình',
        madoituong: 'Mã đối tượng',
        diadiem: 'Địa điểm',
        phanloai: 'Phân loại',
        capquanly: 'Cấp quản lý',
        capkythuat: 'Cấp Kỹ thuật',
        dttuoi: 'Diện tích tưới thiết kế',
        dttieu: 'Diện tích tiêu thiết kế',
        luuluong: 'Lưu lượng',
        donviql: 'Đơn vị quản lý',
        xdstart: 'Năm xây dựng',
        xdend: 'Năm hoàn thành',
        tinhtrang: 'Tình trạng',
        // geo: 'geo',
        nguon: 'Đơn vị cấp thông tin',
        // ngaythunha: 'ngaythunha',
        // ngaycapnha: 'ngaycapnha',
        // phanloai2: 'phanloai2',
    },
    thuydien: {
        // FID: 'FID',
        stt: 'STT',
        ten: 'Tên công trình',
        long: 'Toạ độ X',
        lat: 'Toạ độ Y',
        xa: 'Xã',
        huyen: 'Huyện',
        tinh: 'Tỉnh',
        flv__km2: 'Diện tích lưu vực',
        nlm_mw: 'Công suất lắp máy',
        mntl_m: 'Mực nước thượng lưu',
        w_chet: 'Dung tích chết',
        w_huuich: 'Dung tích hữu ích',
        w_mndbt: 'Dung tích mực nước dâng bình thường',
        w_tong: 'Dung tích tổng cộng',
        mnc: 'Mực nước chết',
        mndbt: 'Mực nước dâng bình thường',
        mndgc: 'Mực nước dâng gia cường',
        nxd: 'Năm xây dựng',
        nht: 'Năm hoàn thành',
        dvql: 'Đơn vị quản lý',
    },
    TuyenChuyenNuoc: {
        FID: 'STT',
        Ten_Tuyen: 'Tên tuyến chuyển nước',
        Muctieu: 'Mục tiêu',
        Tinh: 'Tỉnh',
        Vung: 'Vùng',
        Loai_CT: 'Loại công trình',
        Loaihinh_D: 'Loại hình đầu tư',
        Chieudai_k: 'Chiều dài',
        Qchuyen_m3: 'Lưu lượng',
        Ft_ha: 'Diện tích tưới',
        GD_2030: 'GĐĐT 2030',
        GD_sau2030: 'GĐĐT sau 2030',
        // Ghichu: 'Ghichu',
    },
    congtrinh_xaymoi: {
        // FID: 'FID',
        id: 'STT',
        tenct: 'Tên công trình',
        x: 'Toạ độ X',
        y: 'Toạ độ Y',
        tinh: 'Tỉnh',
        vung: 'Vùng',
        loai_ct: 'Loại công trình',
        loaidautu: 'Loại đầu tư',
        wh_trieum3: 'Dung tích hữu ích',
        ftuoi_ha: 'Diện tích tưới thiết kế',
        chonglu: 'Chống lũ',
        gd_2030: 'GĐĐT 2030',
        gd_sau2030: 'GĐĐT sau 2030',
        ghichu: 'Ghi chú',
        // phanloai1: 'phanloai1',
    },
    CongTrinh_nangcap: {
        // FID: 'FID',
        id: 'STT',
        tenct: 'Tên công trình',
        x: 'Toạ độ X',
        y: 'Toạ độ Y',
        tinh: 'Tỉnh',
        vung: 'Vùng',
        loai_ct: 'Loại công trình',
        loaidautu: 'Loại đầu tư',
        wh_trieum3: 'Dung tích tăng thêm',
        ftuoi_ha: 'Diện tích tưới',
        chonglu: 'Chống lũ',
        gd_2030: 'GĐĐT 2030',
        gd_sau2030: 'GĐĐT sau 2030',
        // ghichu: 'ghichu',
        // phanloai: 'phanloai',
    },
    NangCap_HTTL: {
        // id: 'id',
        tt: 'STT',
        hethong: 'Hệ thống',
        tenct: 'Tên hệ thống',
        muctieu: 'Mục tiêu',
        tinh: 'Tỉnh',
        vung: 'Vùng',
        loai_ct: 'Loại công trình',
        loaihinh_d: 'Loại hình đầu tư',
        ftuoi_ha: 'Diện tích tưới',
        ftieu_ha: 'Diện tích tiêu',
        gd_2030: 'GĐĐT 2030',
        gd_sau2030: 'GĐĐT sau 2030',
        // shape_leng: 'shape_leng',
        // shape_area: 'shape_area',
    }
}

export const configDonvi ={
    hodap_qhqg: {
        // id: 'STT',
        // ten: 'Tên công trình',
        // x: 'Toạ độ X',
        // y: 'Toạ độ Y',
        // Xa: 'Xã',
        // huyen: 'Huyện',
        // tinh: 'Tỉnh',
        // phanloai: 'Phân loại',
        // capquanly: 'Cấp quản lý',
        // capkt: 'Cấp kỹ thuật',
        flv_km2: 'Km2',
        wtb_trm3: 'Triệu m3',
        whi: 'Triệu m3',
        wc: 'Triệu m3',
        wpl_trm3: 'Triệu m3',
        qmay: 'm3/s',
        mndbt: 'm',
        mnc: 'm',
        mnltk: 'm',
        zdinhdap: 'm',
        zdaydap: 'm',
        ldap: 'm',
        // tran: 'Loại tràn',
        // sokhoang: 'Số khoang tràn',
        ztran: 'm',
        btran: 'm',
        // qxa_ltk: 'Lưu lượng xả lũ thiết kế',
        // donviql: 'Đơn vị quản lý',
        // xdstart: 'Năm xây dựng',
        // xdend: 'năm hoàn thành',
        // tinhtrang: 'Tình trạng ',
        // nguon: 'nguon',
        // phanloai1: 'phanloai1',
    },
    cong_qhqg: {
        // id: 'STT',
        // ten: 'Tên công trình',
        // X: 'Toạ độ X',
        // Y: 'Toạ độ Y',
        // xa: 'Xã',
        // tenhuyen: 'Huyện',
        // tentinh: 'Tỉnh',
        // phanloai: 'Phân loại',
        // capquanly: 'Cấp quản lý',
        // capkythuat: 'Cấp kỹ thuật',
        khaudo: 'm',
        Zday: 'm',
        ftuoiha: 'ha',
        ftieuha: 'ha',
        // donviql: 'Đơn vị quản lý',
        // xdstart: 'Năm xây dựng',
        // xdend: 'Năm hoàn thành',
        // tinhtrang: 'tinhtrang',
        // geo: 'geo',
        // nguon: 'nguon',
        // ngaythunha: 'ngaythunha',
        // ngaycapnha: 'ngaycapnha',
        // phanloai1: 'phanloai1',
    },
    trambom_ht:{
        // FID: 'STT',
        // ten: 'Tên công trình',
        // madoituong: 'Mã đối tượng',
        // diadiem: 'Địa điểm',
        // phanloai: 'Phân loại',
        // capquanly: 'Cấp quản lý',
        // capkythuat: 'Cấp Kỹ thuật',
        // dttuoi: 'Diện tích tưới thiết kế',
        // dttieu: 'Diện tích tiêu thiết kế',
        // luuluong: 'Lưu lượng',
        // donviql: 'Đơn vị quản lý',
        // xdstart: 'Năm xây dựng',
        // xdend: 'Năm hoàn thành',
        // tinhtrang: 'Tình trạng',
        // geo: 'geo',
        // nguon: 'Đơn vị cấp thông tin',
        // ngaythunha: 'ngaythunha',
        // ngaycapnha: 'ngaycapnha',
        // phanloai2: 'phanloai2',
    },
    thuydien: {
        // FID: 'FID',
        // stt: 'STT',
        // ten: 'Tên công trình',
        // long: 'Toạ độ X',
        // lat: 'Toạ độ Y',
        // xa: 'Xã',
        // huyen: 'Huyện',
        // tinh: 'Tỉnh',
        flv__km2: 'Km2',
        nlm_mw: 'MW',
        // mntl_m: 'Mực nước thượng lưu',
        // w_chet: 'Dung tích chết',
        // w_huuich: 'Dung tích hữu ích',
        // w_mndbt: 'Dung tích mực nước dâng bình thường',
        // w_tong: 'Dung tích tổng cộng',
        // mnc: 'Mực nước chết',
        // mndbt: 'Mực nước dâng bình thường',
        // mndgc: 'Mực nước dâng gia cường',
        // nxd: 'Năm xây dựng',
        // nht: 'Năm hoàn thành',
        // dvql: 'Đơn vị quản lý',
    },
    TuyenChuyenNuoc: {
        // FID: 'STT',
        // Ten_Tuyen: 'Tên tuyến chuyển nước',
        // Muctieu: 'Mục tiêu',
        // Tinh: 'Tỉnh',
        // Vung: 'Vùng',
        // Loai_CT: 'Loại công trình',
        // Loaihinh_D: 'Loại hình đầu tư',
        Chieudai_k: 'Km',
        Qchuyen_m3: 'm3/s',
        Ft_ha: 'ha',
        // GD_2030: 'GĐĐT 2030',
        // GD_sau2030: 'GĐĐT sau 2030',
        // Ghichu: 'Ghichu',
    },
    congtrinh_xaymoi: {
        // FID: 'FID',
        // id: 'STT',
        // tenct: 'Tên công trình',
        // x: 'Toạ độ X',
        // y: 'Toạ độ Y',
        // tinh: 'Tỉnh',
        // vung: 'Vùng',
        // loai_ct: 'Loại công trình',
        // loaidautu: 'Loại đầu tư',
        wh_trieum3: 'Triệu m3',
        ftuoi_ha: 'ha',
        // chonglu: 'Chống lũ',
        // gd_2030: 'GĐĐT 2030',
        // gd_sau2030: 'GĐĐT sau 2030',
        // ghichu: 'Ghi chú',
        // phanloai1: 'phanloai1',
    },
    CongTrinh_nangcap: {
        // FID: 'FID',
        // id: 'STT',
        // tenct: 'Tên công trình',
        // x: 'Toạ độ X',
        // y: 'Toạ độ Y',
        // tinh: 'Tỉnh',
        // vung: 'Vùng',
        // loai_ct: 'Loại công trình',
        // loaidautu: 'Loại đầu tư',
        wh_trieum3: 'triệu m3',
        ftuoi_ha: 'ha',
        // chonglu: 'Chống lũ',
        // gd_2030: 'GĐĐT 2030',
        // gd_sau2030: 'GĐĐT sau 2030',
        // ghichu: 'ghichu',
        // phanloai: 'phanloai',
    },
    NangCap_HTTL: {
        // id: 'id',
        // tt: 'STT',
        // hethong: 'Hệ thống',
        // tenct: 'Tên hệ thống',
        // muctieu: 'Mục tiêu',
        // tinh: 'Tỉnh',
        // vung: 'Vùng',
        // loai_ct: 'Loại công trình',
        // loaihinh_d: 'Loại hình đầu tư',
        ftuoi_ha: 'ha',
        ftieu_ha: 'ha',
        // gd_2030: 'GĐĐT 2030',
        // gd_sau2030: 'GĐĐT sau 2030',
        // shape_leng: 'shape_leng',
        // shape_area: 'shape_area',
    }
}
